[project]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BioImageAnalysisNotebooks"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
